## some settings and library some necessary packages
setwd("/Users/Janet/Desktop/Coursera/Data Science/4_Exploratory_Data_Analysis/week1_project")
library(data.table)
library(dplyr)
library(lubridate)

##import dataset,subset the necessary data.
data <- fread("./household_power_consumption.txt")
data$Date <- as.Date(data$Date,"%d/%m/%Y")
datasub <- filter(data,Date=="2007-02-01"|Date=="2007-02-02")
datasub$Global_active_power <- as.numeric(datasub$Global_active_power)
datasub <- mutate(datasub,datetime=ymd_hms(paste(Date,Time)))
datasub <- mutate(datasub,weekday=wday(datasub$datetime,label=TRUE))
datasub$Sub_metering_1 <- as.numeric(datasub$Sub_metering_1)
datasub$Sub_metering_2 <- as.numeric(datasub$Sub_metering_2)
datasub$Sub_metering_3 <- as.numeric(datasub$Sub_metering_3)
datasub$Voltage <- as.numeric(datasub$Voltage)
datasub$Global_reactive_power <- as.numeric(datasub$Global_reactive_power)

##use png device to save the plot result.
png(file="plot4.png",width = 480, height = 480,units = "px")
par(mfrow=c(2,2))
with(datasub,{
        plot(datetime,Global_active_power,type="l",xlab="",ylab="Global Active Power")
        axis(1,at=weekday,labels=weekday)
        plot(datetime,Voltage,type="l",xlab="datetime",ylab="Voltage")
        axis(1,at=weekday,labels=weekday)
        plot(datetime,Sub_metering_1,type="l",xlab="",ylab="Energy sub metering")
        axis(1,at=weekday,labels=weekday)
        lines(datetime,Sub_metering_2,,col="red")
        lines(datetime,Sub_metering_3,,col="blue")
        legend("topright",pch="__",col=c("black","red","blue"),,bty="n",legend=c("Sub_metering_1","Sub_metering_2","Sub_metering_3"))
        plot(datetime,Global_reactive_power,type="l",xlab="datetime")
        axis(1,at=weekday,labels=weekday)
})
dev.off()
